FROM golang:latest

WORKDIR /app

# Copy ONLY go.mod first for faster caching
COPY go.mod go.sum ./
RUN go mod download

# Now copy full project
COPY . .

RUN go build -o api ./cmd/server

EXPOSE 8080
CMD ["./api"]
